# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/ms345/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/ms345/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/ms345/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/ms345/proprietary/bin/radish:system/bin/radish \
    vendor/lge/ms345/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/lge/ms345/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/ms345/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/ms345/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/lge/ms345/proprietary/lib/libuicc.so:system/lib/libuicc.so \
    vendor/lge/ms345/proprietary/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
    vendor/lge/ms345/proprietary/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
    vendor/lge/ms345/proprietary/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
    vendor/lge/ms345/proprietary/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
    vendor/lge/ms345/proprietary/lib/libvss_resim_idl.so:system/lib/libvss_resim_idl.so \
    vendor/lge/ms345/proprietary/lib/libvss_resim_iface.so:system/lib/libvss_resim_iface.so \
    vendor/lge/ms345/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/lge/ms345/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/lge/ms345/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/lge/ms345/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/lge/ms345/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/lge/ms345/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/lge/ms345/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/lge/ms345/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/lge/ms345/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/lge/ms345/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lge/ms345/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lge/ms345/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lge/ms345/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lge/ms345/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lge/ms345/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lge/ms345/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt
